### ISSUE TITLE
CẦN TRỢ GIÚP

### ISSUE THREAD

**Issue by MeoNguOfficial** [motcainit/Thesieutoc#10]
Tôi cần cải thiện menu nạp thẻ (không hiện các tiền tố link ở chat)
Plugin tôi dùng: Command Panels

https://github.com/motcainit/Thesieutoc/assets/135810477/5cef4586-02fa-43c9-badd-5fb8c8e5dcd2

Menu chọn loại thẻ (File YAML):
`panels:
  chon_loai_the:
    perm: default
    rows: 6
    title: '&2&lDONATE - CHỌN LOẠI THẺ'
    sound-on-open: ENTITY_EXPERIENCE_ORB_PICKUP
    commands:
      - ungho111
      - donate111
      - napthe111
    empty: BLACK_STAINED_GLASS_PANE
    item:
      '0':
        material: GREEN_STAINED_GLASS_PANE
        stack: 1
      '1':
        material: GREEN_STAINED_GLASS_PANE
        stack: 1
      '2':
        material: GREEN_STAINED_GLASS_PANE
        stack: 1
      '3':
        material: GREEN_STAINED_GLASS_PANE
        stack: 1
      '4':
        material: GREEN_STAINED_GLASS_PANE
        stack: 1
      '5':
        material: GREEN_STAINED_GLASS_PANE
        stack: 1
      '6':
        material: GREEN_STAINED_GLASS_PANE
        stack: 1
      '7':
        material: GREEN_STAINED_GLASS_PANE
        stack: 1
      '8':
        material: GREEN_STAINED_GLASS_PANE
        stack: 1
      '9':
        material: cps= MeoNgu2
        stack: 1
      '10':
        material: GREEN_STAINED_GLASS_PANE
        stack: 1
      '11':
        material: WRITABLE_BOOK
        stack: 1
        name: '&c&lCHỌN THẺ &e&lVIETTEL'
        lore:
        - §b--------------------------------------------
        - '&a&lHỗ trợ từ 10.000 VNĐ đến 1.000.000 VNĐ' 
        - '&aClick để chọn'
        - §b--------------------------------------------
        - '&a&lTình trạng: &6&lĐang chạy'
        - §b--------------------------------------------
        commands:
        - napthe textchoosecard Viettel
        - console= cp chon_menh_gia %player_name%
      '12':
        material: WHITE_STAINED_GLASS_PANE
        stack: 1
      '13':
        material: WRITABLE_BOOK
        stack: 1
        name: '&c&lCHỌN THẺ &e&lVINAPHONE'
        lore:
        - §b--------------------------------------------
        - '&a&lHỗ trợ từ 10.000 VNĐ đến 1.000.000 VNĐ' 
        - '&aClick để chọn'
        - §b--------------------------------------------
        - '&a&lTình trạng: &6&lĐang chạy'
        - §b--------------------------------------------
        commands:
        - napthe textchoosecard Vinaphone
        - console= cp chon_menh_gia %player_name%
      '14':
        material: WHITE_STAINED_GLASS_PANE
        stack: 1
      '15':
        material: WRITABLE_BOOK
        stack: 1
        name: '&c&lCHỌN THẺ &e&lMOBIFONE'
        lore:
        - §b--------------------------------------------
        - '&a&lHỗ trợ từ 10.000 VNĐ đến 1.000.000 VNĐ' 
        - '&aClick để chọn'
        - §b--------------------------------------------
        - '&a&lTình trạng: &6&lĐang chạy'
        - §b--------------------------------------------
        commands:
        - napthe textchoosecard Mobifone
        - console= cp chon_menh_gia %player_name%
      '16':
        material: WHITE_STAINED_GLASS_PANE
        stack: 1
      '17':
        material: WRITABLE_BOOK
        stack: 1
        name: '&c&lCHỌN THẺ &e&lVIETNAMMOBILE'
        lore:
        - §b--------------------------------------------
        - '&a&lHỗ trợ từ 10.000 VNĐ đến 1.000.000 VNĐ' 
        - '&aClick để chọn'
        - §b--------------------------------------------
        - '&a&lTình trạng: &6&lĐang chạy'
        - §b--------------------------------------------
        commands:
        - napthe textchoosecard Vietnammobile
        - console= cp chon_menh_gia %player_name%
      '18':
        material: cps= MeoNgu2
        stack: 1
      '19':
        material: GREEN_STAINED_GLASS_PANE
        stack: 1
      '20':
        material: WHITE_STAINED_GLASS_PANE
        stack: 1
      '21':
        material: WHITE_STAINED_GLASS_PANE
        stack: 1
      '22':
        material: WHITE_STAINED_GLASS_PANE
        stack: 1
      '23':
        material: WHITE_STAINED_GLASS_PANE
        stack: 1
      '24':
        material: WHITE_STAINED_GLASS_PANE
        stack: 1
      '25':
        material: WHITE_STAINED_GLASS_PANE
        stack: 1
      '26':
        material: WHITE_STAINED_GLASS_PANE
        stack: 1
      '27':
        material: cps= MeoNgu2
        stack: 1
      '28':
        material: GREEN_STAINED_GLASS_PANE
        stack: 1
      '29':
        material: WRITABLE_BOOK
        stack: 1
        name: '&c&lCHỌN THẺ &e&lGATE'
        lore:
        - §b--------------------------------------------
        - '&a&lHỗ trợ từ 10.000 VNĐ đến 1.000.000 VNĐ' 
        - '&aClick để chọn'
        - §b--------------------------------------------
        - '&a&lTình trạng: &6&lĐang chạy'
        - §b--------------------------------------------
        commands:
        - napthe textchoosecard Gate
        - console= cp chon_menh_gia %player_name%
      '30':
        material: WHITE_STAINED_GLASS_PANE
        stack: 1
      '31':
        material: WRITABLE_BOOK
        stack: 1
        name: '&c&lCHỌN THẺ &e&lGARENA'
        lore:
        - §b--------------------------------------------
        - '&a&lHỗ trợ từ 10.000 VNĐ đến 1.000.000 VNĐ' 
        - '&aClick để chọn'
        - §b--------------------------------------------
        - '&a&lTình trạng: &6&lĐang chạy'
        - §b--------------------------------------------
        commands:
        - napthe textchoosecard Garena
        - console= cp chon_menh_gia %player_name%
      '32':
        material: WHITE_STAINED_GLASS_PANE
        stack: 1
      '33':
        material: WRITABLE_BOOK
        stack: 1
        name: '&c&lCHỌN THẺ &e&lVCOIN'
        lore:
        - §b--------------------------------------------
        - '&a&lHỗ trợ từ 10.000 VNĐ đến 1.000.000 VNĐ' 
        - '&aClick để chọn'
        - §b--------------------------------------------
        - '&a&lTình trạng: &6&lĐang chạy'
        - §b--------------------------------------------
        commands:
        - napthe textchoosecard VCoin
        - console= cp chon_menh_gia %player_name%
      '34':
        material: WHITE_STAINED_GLASS_PANE
        stack: 1
      '35':
        material: WRITABLE_BOOK
        stack: 1
        name: '&c&lCHỌN THẺ &e&lZING'
        lore:
        - §b--------------------------------------------
        - '&a&lHỗ trợ từ 10.000 VNĐ đến 1.000.000 VNĐ' 
        - '&aClick để chọn'
        - §b--------------------------------------------
        - '&a&lTình trạng: &6&lĐang chạy'
        - §b--------------------------------------------
        commands:
        - napthe textchoosecard Zing
        - console= cp chon_menh_gia %player_name%
      '36':
        material: GREEN_STAINED_GLASS_PANE
        stack: 1
      '37':
        material: GREEN_STAINED_GLASS_PANE
        stack: 1
      '38':
        material: GREEN_STAINED_GLASS_PANE
        stack: 1
      '39':
        material: GREEN_STAINED_GLASS_PANE
        stack: 1
      '40':
        material: GREEN_STAINED_GLASS_PANE
        stack: 1
      '41':
        material: GREEN_STAINED_GLASS_PANE
        stack: 1
      '42':
        material: GREEN_STAINED_GLASS_PANE
        stack: 1
      '43':
        material: GREEN_STAINED_GLASS_PANE
        stack: 1
      '44':
        material: GREEN_STAINED_GLASS_PANE
        stack: 1
      '45':
        material: BARRIER
        stack: 1
      '46':
        material: GREEN_STAINED_GLASS_PANE
        stack: 1
      '47':
        material: WHITE_STAINED_GLASS_PANE
        stack: 1
      '48':
        material: WHITE_STAINED_GLASS_PANE
        stack: 1
      '49':
        material: WHITE_STAINED_GLASS_PANE
        stack: 1
      '50':
        material: WHITE_STAINED_GLASS_PANE
        stack: 1
      '51':
        material: WHITE_STAINED_GLASS_PANE
        stack: 1
      '52':
        material: WHITE_STAINED_GLASS_PANE
        stack: 1
      '53':
        material: WHITE_STAINED_GLASS_PANE
        stack: 1
`
Menu chọn mệnh giá: (File YAML)
`panels:
  chon_menh_gia:
    perm: default
    rows: 6
    title: '&2&lDONATE - CHỌN VIETTEL'
    sound-on-open: ENTITY_EXPERIENCE_ORB_PICKUP
    empty: BLACK_STAINED_GLASS_PANE
    item:
      '0':
        material: YELLOW_STAINED_GLASS_PANE
        stack: 1
      '1':
        material: YELLOW_STAINED_GLASS_PANE
        stack: 1
      '2':
        material: YELLOW_STAINED_GLASS_PANE
        stack: 1
      '3':
        material: YELLOW_STAINED_GLASS_PANE
        stack: 1
      '4':
        material: YELLOW_STAINED_GLASS_PANE
        stack: 1
      '5':
        material: YELLOW_STAINED_GLASS_PANE
        stack: 1
      '6':
        material: YELLOW_STAINED_GLASS_PANE
        stack: 1
      '7':
        material: YELLOW_STAINED_GLASS_PANE
        stack: 1
      '8':
        material: YELLOW_STAINED_GLASS_PANE
        stack: 1
      '9':
        material: cps= MeoNgu2
        stack: 1
      '10':
        material: YELLOW_STAINED_GLASS_PANE
        stack: 1
      '11':
        material: WHITE_STAINED_GLASS_PANE
        stack: 1
      '12':
        material: PAPER
        stack: 1
        name: '&e&lCHỌN MỆNH GIÁ &b&l10.000 VNĐ'
        lore:
        - §b--------------------------------------------' 
        - '&aClick để chọn'
        - '&c&lChú ý: &6&lVui lòng thực hiện theo hướng dẫn'
        - §b--------------------------------------------
        commands:
        - napthe textchoosecardprice 10000
        - cpc
      '13':
        material: WHITE_STAINED_GLASS_PANE
        stack: 1
      '14':
        material: PAPER
        stack: 1
        name: '&e&lCHỌN MỆNH GIÁ &b&l20.000 VNĐ'
        lore:
        - §b--------------------------------------------' 
        - '&aClick để chọn'
        - '&c&lChú ý: &6&lVui lòng thực hiện theo hướng dẫn'
        - §b--------------------------------------------
        commands:
        - napthe textchoosecardprice 20000
        - cpc
      '15':
        material: WHITE_STAINED_GLASS_PANE
        stack: 1
      '16':
        material: PAPER
        stack: 1
        name: '&e&lCHỌN MỆNH GIÁ &b&l30.000 VNĐ'
        lore:
        - §b--------------------------------------------' 
        - '&aClick để chọn'
        - '&c&lChú ý: &6&lVui lòng thực hiện theo hướng dẫn'
        - §b--------------------------------------------
        commands:
        - napthe textchoosecardprice 30000
        - cpc
      '17':
        material: WHITE_STAINED_GLASS_PANE
        stack: 1
      '18':
        material: cps= MeoNgu2
        stack: 1
      '19':
        material: YELLOW_STAINED_GLASS_PANE
        stack: 1
      '20':
        material: PAPER
        stack: 1
        name: '&e&lCHỌN MỆNH GIÁ &b&l50.000 VNĐ'
        lore:
        - §b--------------------------------------------' 
        - '&aClick để chọn'
        - '&c&lChú ý: &6&lVui lòng thực hiện theo hướng dẫn'
        - §b--------------------------------------------
        commands:
        - napthe textchoosecardprice 50000
        - cpc
      '21':
        material: WHITE_STAINED_GLASS_PANE
        stack: 1
      '22':
        material: PAPER
        stack: 1
        name: '&e&lCHỌN MỆNH GIÁ &b&l100.000 VNĐ'
        lore:
        - §b--------------------------------------------' 
        - '&aClick để chọn'
        - '&c&lChú ý: &6&lVui lòng thực hiện theo hướng dẫn'
        - §b--------------------------------------------
        commands:
        - napthe textchoosecardprice 100000
        - cpc
      '23':
        material: WHITE_STAINED_GLASS_PANE
        stack: 1
      '24':
        material: PAPER
        stack: 1
        name: '&e&lCHỌN MỆNH GIÁ &b&l200.000 VNĐ'
        lore:
        - §b--------------------------------------------' 
        - '&aClick để chọn'
        - '&c&lChú ý: &6&lVui lòng thực hiện theo hướng dẫn'
        - §b--------------------------------------------
        commands:
        - napthe textchoosecardprice 200000
        - cpc
      '25':
        material: WHITE_STAINED_GLASS_PANE
        stack: 1
      '26':
        material: PAPER
        stack: 1
        name: '&e&lCHỌN MỆNH GIÁ &b&l300.000 VNĐ'
        lore:
        - §b--------------------------------------------' 
        - '&aClick để chọn'
        - '&c&lChú ý: &6&lVui lòng thực hiện theo hướng dẫn'
        - §b--------------------------------------------
        commands:
        - napthe textchoosecardprice 300000
        - cpc
      '27':
        material: cps= MeoNgu2
        stack: 1
      '28':
        material: YELLOW_STAINED_GLASS_PANE
        stack: 1
      '29':
        material: WHITE_STAINED_GLASS_PANE
        stack: 1
      '30':
        material: PAPER
        stack: 1
        name: '&e&lCHỌN MỆNH GIÁ &b&l500.000 VNĐ'
        lore:
        - §b--------------------------------------------' 
        - '&aClick để chọn'
        - '&c&lChú ý: &6&lVui lòng thực hiện theo hướng dẫn'
        - §b--------------------------------------------
        commands:
        - napthe textchoosecardprice 500000
        - cpc
      '31':
        material: WHITE_STAINED_GLASS_PANE
        stack: 1
      '32':
        material: PAPER
        stack: 1
        name: '&e&lCHỌN MỆNH GIÁ &b&l1.000.000 VNĐ'
        lore:
        - §b--------------------------------------------' 
        - '&aClick để chọn'
        - '&c&lChú ý: &6&lVui lòng thực hiện theo hướng dẫn'
        - §b--------------------------------------------
        commands:
        - napthe textchoosecardprice 1000000
        - cpc
      '33':
        material: WHITE_STAINED_GLASS_PANE
        stack: 1
      '34':
        material: acacia_hanging_sign
        stack: 1
        name: '&a&lCHUYỂN KHOẢN'
      '35':
        material: WHITE_STAINED_GLASS_PANE
        stack: 1
      '36':
        material: YELLOW_STAINED_GLASS_PANE
        stack: 1
      '37':
        material: YELLOW_STAINED_GLASS_PANE
        stack: 1
      '38':
        material: YELLOW_STAINED_GLASS_PANE
        stack: 1
      '39':
        material: YELLOW_STAINED_GLASS_PANE
        stack: 1
      '40':
        material: YELLOW_STAINED_GLASS_PANE
        stack: 1
      '41':
        material: YELLOW_STAINED_GLASS_PANE
        stack: 1
      '42':
        material: YELLOW_STAINED_GLASS_PANE
        stack: 1
      '43':
        material: YELLOW_STAINED_GLASS_PANE
        stack: 1
      '44':
        material: YELLOW_STAINED_GLASS_PANE
        stack: 1
      '45':
        material: BARRIER
        stack: 1
        name: Quay lại
      '46':
        material: YELLOW_STAINED_GLASS_PANE
        stack: 1
      '47':
        material: WHITE_STAINED_GLASS_PANE
        stack: 1
      '48':
        material: WHITE_STAINED_GLASS_PANE
        stack: 1
      '49':
        material: WHITE_STAINED_GLASS_PANE
        stack: 1
      '50':
        material: WHITE_STAINED_GLASS_PANE
        stack: 1
      '51':
        material: WHITE_STAINED_GLASS_PANE
        stack: 1
      '52':
        material: WHITE_STAINED_GLASS_PANE
        stack: 1
      '53':
        material: WHITE_STAINED_GLASS_PANE
        stack: 1
`
Mong được giúp đỡ

**Comment by motcainit** [comment]
Bạn dùng config của DeluxeMenus được mình đính kèm theo plugin lúc tải nha
