### ISSUE TITLE
Tôi cần ô fix lại menu nạp thẻ của plugin Thesieutoc

### ISSUE THREAD

**Issue by Udjfjjfd** [motcainit/Thesieutoc#11]
Cụ thể là khi tôi ghi lệnh /napthe nó hiện menu chọn hình thức nạp 
Tôi chọn Viettel r chọn mệnh giá thẻ thì nó không hiện menu nhập số
Seri và Mả thẻ 
Ô có thể xem video:

https://github.com/motcainit/Thesieutoc/assets/133106121/32d5edf8-d63c-4521-bff1-67c038e0746f

**Comment by motcainit** [comment]
Bạn tải bản mới nhất nha, hỗ trợ đến 1.21.2

**Comment by Udjfjjfd** [comment]
Okok

Vào 02:42 T.3, 12 Th11, 2024 motcainit ***@***.***> đã viết:
