### ISSUE TITLE
Hỗ trợ MySQL 8!

### ISSUE THREAD

**Issue by SunshroomChan** [motcainit/Thesieutoc#3]
Mình dùng TheSieuToc nhưng muốn đồng bộ với MySQL nhưng có một số vấn đề là từ Spigot 1.8 đến 1.16.4 thì họ dùng MySQL 5 thay vì là MySQL 8 cho đến khi từ 1.16.5 thì Spigot nó sử dụng MySQL 8 đổ lên thì mong AD có thể mở source code hoặc thêm hỗ trợ Driver của MySQL 8 và đa số mọi người đều dùng MySQL 8 nên điều này dễ hiểu!

**Comment by motcainit** [comment]
Đã hỗ trợ nha.

**Comment by SunshroomChan** [comment]
lỗi MySQL 8 vẫn còn nhé bạn nếu chạy 1.12.2, bạn nên thêm driver vào trong plugin làm library nếu bạn build bằng Maven ạ! Chứ mình cho xem code trong jar file hơi khó hiểu ạ

**Comment by motcainit** [comment]
Bạn cho mình xin thông tin phiên bản máy chủ & phiên bản java của bạn với, mình đã thử trên 3 phiên bản paper là 1.8.8, 1.12.2 và 1.20.2 đều sử dụng được.

**Comment by motcainit** [comment]
Đã thử chuyển sang dùng HikariCP, mình đã test trên phiên bản 1.20.2 và Java 17, bạn xài thử bản #35 xem sao.

**Comment by SunshroomChan** [comment]
> Đã thử chuyển sang dùng HikariCP, mình đã test trên phiên bản 1.20.2 và Java 17, bạn xài thử bản #35 xem sao.

Lúc mình có chạy bên 1.12.2 thì plugin báo là không có Class MySQDataSource 2 gì đó rồi plugin tự tắt nhé bạn
