### ISSUE TITLE
Fix lỗi này đi ad

### ISSUE THREAD

**Issue by MeoNguOfficial** [motcainit/Thesieutoc#4]
Lỗi này quá chí mạng luôn
![image](https://github.com/motcainit/Thesieutoc/assets/135810477/885229ee-67ab-4a06-9867-445f8e94f058)

**Comment by MeoNguOfficial** [comment]
Ở đâu ra thư mục log_success.txt mà dạng thư mục vậy?

**Comment by motcainit** [comment]
đã sửa ở bản #32
