### ISSUE TITLE
Một vài kí tự không đọc được

### ISSUE THREAD

**Issue by MeoNguOfficial** [motcainit/Thesieutoc#5]
Tôi nhập /tst để xem hướng dẫn mà kết quả không ngờ
Ngôn ngữ tôi dùng là tiếng Anh - United Kingdom
Unicode: Không bật
Phiên bản Thẻ siêu tốc: v33
![image](https://github.com/motcainit/Thesieutoc/assets/135810477/e6fcc2c3-99d6-4ee8-bc7e-0bcd9c3881fd)

**Comment by motcainit** [comment]
Bạn up lên bản v34 sẽ hết nha

**Comment by MeoNguOfficial** [comment]
Dạ để check!
