### ISSUE TITLE
Nạp thẻ bị treo

### ISSUE THREAD

**Issue by ngththuyen** [motcainit/Thesieutoc#7]
Máy chủ của mình có sử dụng plugin thesieutoc phiên bản mới nhất và dạo gần đây lại xuất hiện một số tình trạng là thẻ bị treo 5p rồi sau đó nhập lại thẻ đó thì thẻ đã tồn tại trên hệ thống và mem lẫn mình không nhận được gì. Cho mình hỏi là cái này nguyên nhân do đâu và có biện pháp khắc phục không ạ

**Comment by motcainit** [comment]
Nếu bạn dùng bản cũ hơn #35 thì plugin hiện đang dùng api server của cloudflare nên có thể sẽ không trả được thông tin thẻ.

Còn bản #35 trở đi thì đã dùng api server của VNPT, bạn kiểm tra Firewall có chặn ip 103.153.73.105 không nha

**Comment by ngththuyen** [comment]
à với lại member mình báo khi nạp thẻ trong lúc chờ duyệt thẻ mà nhấn nạp 1 lần nữa chọn mệnh giá cao hơn thì sẽ nhận được phần thưởng ở mệnh giá cao hơn ấy ( server mình nạp thẻ không sử dụng gui ). Bạn kiểm tra thử xem có lỗi đó không.

Phiên bản plugin: mới nhất
Phiên bản Minecraft: 1.18.2

**Comment by motcainit** [comment]
> à với lại member mình báo khi nạp thẻ trong lúc chờ duyệt thẻ mà nhấn nạp 1 lần nữa chọn mệnh giá cao hơn thì sẽ nhận được phần thưởng ở mệnh giá cao hơn ấy ( server mình nạp thẻ không sử dụng gui ). Bạn kiểm tra thử xem có lỗi đó không.
> 
> Phiên bản plugin: mới nhất Phiên bản Minecraft: 1.18.2

Đã sửa lỗi trong bản #37 nha
