### ISSUE TITLE
Menu tst

### ISSUE THREAD

**Issue by quocn9043** [motcainit/Thesieutoc#8]
Làm sao add menu nạp thẻ cho tst vậy bạn , sao mình tải về ko thấy nó khá bất tiện cho pe á vì pe ấn vô dòng chọn card trên chat k đc

**Comment by motcainit** [comment]
Mình thấy có 1 bạn khác có làm phiên bản hỗ trợ PE, bạn tải về xài chung với plugin chính nha.
https://github.com/HuynhKhanh1402/TheSieuTocForm

**Comment by MeoNguOfficial** [comment]
Có menu Thẻ siêu tốc không ạ? Xin với
