### ISSUE TITLE
Bug mệnh giá 10,000 VNĐ Mobiphone

### ISSUE THREAD

**Issue by hiiamken** [motcainit/Thesieutoc#9]
Mình đang gặp trường hợp 1 đứa trong server nạp thẻ Mobiphone 10k nhưng trong game plugin lại tính 1 triệu
Nó nạp 6 lần liên tiếp và plugin tính là tổng 6 triệu
Mình không biết các thẻ khác có bị không, mình thử nạp thì vẫn tính là 10k. Không biết nó bug như nào
![image](https://github.com/motcainit/Thesieutoc/assets/142149960/51a1f3ed-d3c3-4541-94d6-b983b426dbb8)
![image](https://github.com/motcainit/Thesieutoc/assets/142149960/302113b6-69ed-4706-a9b2-7f7fa4182a35)

**Comment by motcainit** [comment]
Bạn xài plugin phiên bản nào ạ

**Comment by hiiamken** [comment]
Mình sài mới nhất #37 luôn ấy ạ, cứ có update là mình cài update. Folder cũng là folder mới luôn

**Comment by hiiamken** [comment]
Cái này thì mem nó báo có đứa vừa nạp 5 triệu thì mình mới check log thì check đúng 5 lần 1,000,000 thật nhưng check web thì nó lại là 10,000 VNĐ. Nó nạp 1 lần hôm trước rồi nên mình nghĩ nó biết bug nên hôm sau nó nạp 5 cái liên tiếp

**Comment by motcainit** [comment]
Bạn có bật debug trong config không, nếu có thì gửi file log riêng cho mình (Discord: projectzip)

**Comment by hiiamken** [comment]
Mình không bật tại cái này mình phát hiện sau 1 ngày, đứa kia thì nó cũng out server luôn r

**Comment by motcainit** [comment]
Vậy bạn bật lên đi, chứ hiện tại không xác định được bug chỗ nào nên mình cũng không thể fix được ạ

**Comment by motcainit** [comment]
Bạn tải bản mới #38 về nha

**Comment by hiiamken** [comment]
Tìm ra được nguyên nhân r đk ạ
